package com.example.android_app.presentation.company.jobposting

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.android_app.data.models.Job
import com.example.android_app.data.services.JobService
import com.google.firebase.auth.FirebaseAuth
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch




class JobPostingViewModel : ViewModel() {

    private val jobService = JobService()
    private val auth = FirebaseAuth.getInstance()

    private val _uiState = MutableStateFlow(JobPostingUiState())
    val uiState: StateFlow<JobPostingUiState> = _uiState.asStateFlow()

    fun onTitleChange(newValue: String) {
        _uiState.update { it.copy(title = newValue) }
    }

    fun onLocationChange(newValue: String) {
        _uiState.update { it.copy(location = newValue) }
    }

    fun onSalaryChange(newValue: String) {
        _uiState.update { it.copy(salary = newValue) }
    }

    fun onDescriptionChange(newValue: String) {
        _uiState.update { it.copy(description = newValue) }
    }

    fun onResponsibilitiesChange(newValue: String) {
        _uiState.update { it.copy(responsibilities = newValue) }
    }

    fun onRequirementsChange(newValue: String) {
        _uiState.update { it.copy(requirements = newValue) }
    }

    fun onJobTypeChange(newValue: String) {
        _uiState.update { it.copy(selectedJobType = newValue) }
    }

    fun onPostJob() {
        val currentState = _uiState.value
        val userId = auth.currentUser?.uid

        if (userId == null) {
            _uiState.update { it.copy(errorMessage = "User not logged in") }
            return
        }

        if (currentState.title.isBlank() || currentState.location.isBlank()) {
             _uiState.update { it.copy(errorMessage = "Title and Location are required") }
            return
        }

        viewModelScope.launch {
            _uiState.update { it.copy(isLoading = true, errorMessage = null) }

            // Job object construction based on the model.
            // Note: id is generated by Firestore, companyId is the authenticated user.
            val newJob = Job(
                companyId = userId,
                title = currentState.title,
                location = currentState.location,
                salary = currentState.salary,
                description = currentState.description,
                responsibilities = currentState.responsibilities,
                requirements = currentState.requirements,
                jobType = currentState.selectedJobType
            )

            val result = jobService.createJob(userId, newJob)

            if (result.isSuccess) {
                _uiState.update { it.copy(isLoading = false, isPostSuccess = true) }
            } else {
                _uiState.update { 
                    it.copy(
                        isLoading = false, 
                        errorMessage = result.exceptionOrNull()?.message ?: "Failed to post job"
                    ) 
                }
            }
        }
    }
    
    fun resetState() {
        _uiState.value = JobPostingUiState()
    }
}
